/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface IConfig {
  followSymlinks?: boolean
  maxDepth?: number
  minDepth?: number
}
export function walkdir(entry: string, callback: (path: string) => void): void
export function walkdirWithConfig(entry: string, config: IConfig, callback: (path: string) => void): void
